version: '3.8'

services:

  # 1. MongoDB (Database)
  mongo:
    image: mongo:latest
    container_name: fitness-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    restart: always # <-- Added this
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    container_name: fitness-postgres
    ports:
      - "5433:5432"
    restart: always # <-- Added this
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # 2. Redis (Cache)
  redis:
    image: redis/redis-stack:latest
    container_name: fitness-redis
    ports:
      - "6380:6379"
      - "8001:8001"
    restart: always

  # 3. Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 4. Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 5. RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  # ---------------- MICROSERVICES ----------------

  # 6. Discovery Server
  discovery-service:
    build: ./eureka
    container_name: discovery-service
    ports:
      - "8761:8761"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # 7. Config Server
  config-service:
    build: ./configserver
    container_name: config-service
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
    restart: always
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  # 8. User Service
  user-service:
    build: ./userService
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - discovery-service
      - config-service
    restart: always # <-- Agar Config server late hua to ye retry karega
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888

  # 9. Activity Service (STAR PLAYER â­)
  activity-service:
    build: ./activityservice
    container_name: activity-service
    ports:
      - "8082:8082"
    depends_on:
      mongo:
        condition: service_healthy
      kafka:
        condition: service_started
      discovery-service:
        condition: service_started
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_ENABLED=false
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  # 10. AI Service
  ai-service:
    build: ./aiservice
    container_name: ai-service
    ports:
      - "8083:8083"
    depends_on:
      - mongo
      - kafka
      - discovery-service
      - config-service
    restart: always
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - GEMINI_KEY=${GEMINI_KEY}
      - GEMINI_URL=${GEMINI_URL}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888

  # 11. Orchestrator Service
  orchestrator-service:
    build: ./orchestrator-service
    container_name: orchestrator-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - rabbitmq
      - discovery-service
      - config-service
    restart: always
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_RABBITMQ_HOST=${RABBITMQ_HOST}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888

  # 12. Notification Service
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8085:8085"
    depends_on:
      - rabbitmq
      - discovery-service
      - config-service
    restart: always
    environment:
      - SPRING_RABBITMQ_HOST=${RABBITMQ_HOST}
      - SPRING_MAIL_USERNAME=${GMAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${GMAIL_APP_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888

  # 13. Analytics Service
  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    ports:
      - "8086:8086"
    depends_on:
      - redis
      - kafka
      - discovery-service
      - config-service
    restart: always
    environment:
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888

  # 14. API Gateway
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - user-service
      - activity-service
      - config-service
    restart: always
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888

volumes:
  mongo-data:
  postgres-data: